- name: CSV Driven Out-of-Place Restore
  hosts: localhost
  gather_facts: false
  vars:
    csv_file_path: "./restore_guid.csv"
    regex_strip_quotes: "^['\"]?(.*?)['\"]?$"

  tasks:
    - name: Log in to the Commcell
      commvault.ansible.login:
        webserver_hostname: "{{ http_hostname }}"
        commcell_username: "{{ http_username }}"
        commcell_password: "{{ http_password }}"
        verify_ssl: false
      register: login_response

    - name: Read CSV file
      community.general.read_csv:
        path: "{{ csv_file_path }}"
      register: csv_data

    - name: Run restore for each item in CSV
      ansible.builtin.include_tasks: restore_task_guid.yml
      loop: "{{ csv_data.list }}"
      loop_control:
        loop_var: item
        label: "{{ item.client_name }}"
