- name: CSV Driven Out-of-Place Restore
  hosts: localhost
  gather_facts: false
  vars:
    csv_file_path: "./restore.csv"
    regex_strip_quotes: "^['\"]?(.*?)['\"]?$"

  tasks:
    - name: Read CSV file
      community.general.read_csv:
        path: "{{ csv_file_path }}"
      register: csv_data

    - name: Run restore for each item in CSV
      ansible.builtin.include_tasks: restore_task.yml
      loop: "{{ csv_data.list }}"
      loop_control:
        loop_var: item
        label: "{{ item.client_name }}"
