- name: Comparison of captured services
  block:
    # Step 1: Slurp all four files
    - name: Slurp running services BEFORE patch
      ansible.builtin.slurp:
        src: "{{ rhel_ol_patch_running_before }}"
      register: running_before_slurped

    - name: Slurp running services AFTER patch
      ansible.builtin.slurp:
        src: "{{ rhel_ol_patch_running_after }}"
      register: running_after_slurped

    - name: Slurp enabled services BEFORE patch
      ansible.builtin.slurp:
        src: "{{ rhel_ol_patch_enabled_before }}"
      register: enabled_before_slurped

    - name: Slurp enabled services AFTER patch
      ansible.builtin.slurp:
        src: "{{ rhel_ol_patch_enabled_after }}"
      register: enabled_after_slurped

    # Step 2: Decode base64, trim whitespace, and split lines
    - name: Decode and normalize service data
      ansible.builtin.set_fact:
        running_before: "{{ running_before_slurped.content | b64decode | split('\n') | map('trim') | reject('equalto', '') | list | sort }}"
        running_after: "{{ running_after_slurped.content | b64decode | split('\n') | map('trim') | reject('equalto', '') | list | sort }}"
        enabled_before: "{{ enabled_before_slurped.content | b64decode | split('\n') | map('trim') | reject('equalto', '') | list | sort }}"
        enabled_after: "{{ enabled_after_slurped.content | b64decode | split('\n') | map('trim') | reject('equalto', '') | list | sort }}"

    # Step 3: Run fact_diff on running and enabled services
    - name: Compare RUNNING before vs after
      ansible.utils.fact_diff:
        before: "{{ running_before }}"
        after: "{{ running_after }}"
      register: diff_running
      when: running_before != running_after

    - name: Compare ENABLED before vs after
      ansible.utils.fact_diff:
        before: "{{ enabled_before }}"
        after: "{{ enabled_after }}"
      register: diff_enabled
      when: enabled_before != enabled_after
