- name: Comparison of captured services
  block:

    # Step 1: Load service lists using slurp
    - name: Slurp running services before patch
      ansible.builtin.slurp:
        src: "{{ rhel_ol_patch_running_before }}"
      register: running_before_slurped

    - name: Slurp running services after patch
      ansible.builtin.slurp:
        src: "{{ rhel_ol_patch_running_after }}"
      register: running_after_slurped

    - name: Slurp enabled services before patch
      ansible.builtin.slurp:
        src: "{{ rhel_ol_patch_enabled_before }}"
      register: enabled_before_slurped

    - name: Slurp enabled services after patch
      ansible.builtin.slurp:
        src: "{{ rhel_ol_patch_enabled_after }}"
      register: enabled_after_slurped

    # Step 2: Decode base64 content into service lists
    - name: Decode slurped data
      ansible.builtin.set_fact:
        running_before: "{{ running_before_slurped.content | b64decode | splitlines() | reject('equalto', '') | list }}"
        running_after: "{{ running_after_slurped.content | b64decode | splitlines() | reject('equalto', '') | list }}"
        enabled_before: "{{ enabled_before_slurped.content | b64decode | splitlines() | reject('equalto', '') | list }}"
        enabled_after: "{{ enabled_after_slurped.content | b64decode | splitlines() | reject('equalto', '') | list }}"

    # Step 3: Use ansible.utils.fact_diff module
    - name: Run fact_diff on running services
      ansible.utils.fact_diff:
        before: "{{ running_before }}"
        after: "{{ running_after }}"
      register: running_diff
      when: running_before != running_after

    - name: Run fact_diff on enabled services
      ansible.utils.fact_diff:
        before: "{{ enabled_before }}"
        after: "{{ enabled_after }}"
      register: enabled_diff
      when: enabled_before != enabled_after

    # Step 4: Show diff output
    - name: Show diff for running services
      ansible.builtin.debug:
        var: running_diff.diff_lines
      when: running_before != running_after

    - name: Show diff for enabled services
      ansible.builtin.debug:
        var: enabled_diff.diff_lines
      when: enabled_before != enabled_after