---
- name: Gather post-patch network routes, mounted filesystems, and IP addresses
  block:

    - name: Gather network, mount, system, and hardware facts after patch
      ansible.builtin.setup:
        gather_subset:
          - network
          - mounts
          - hardware
          - system
      register: post_patch_facts

    - name: Compare full system facts (pre vs post patch)
      ansible.utils.fact_diff:
        before: "{{ pre_patch_facts.ansible_facts }}"
        after: "{{ post_patch_facts.ansible_facts }}"
      register: full_fact_diff

    - name: Print full fact difference (if any)
      ansible.builtin.debug:
        var: full_fact_diff.diff_lines
      when: full_fact_diff.diff_lines | length > 0

    - name: Compare kernel versions
      ansible.builtin.debug:
        msg: |
          Kernel before patch: {{ pre_patch_facts.ansible_facts.ansible_kernel }}
          Kernel after patch:  {{ post_patch_facts.ansible_facts.ansible_kernel }}

    - name: Compare OS release info
      ansible.builtin.debug:
        msg: |
          OS before patch: {{ pre_patch_facts.ansible_facts.ansible_distribution }} {{ pre_patch_facts.ansible_facts.ansible_distribution_version }}
          OS after patch:  {{ post_patch_facts.ansible_facts.ansible_distribution }} {{ post_patch_facts.ansible_facts.ansible_distribution_version }}
