name: Ansible Playbook Linting

on:
  push:
    paths:
      - '**.yml'
      - '**.yaml'
  pull_request:
    paths:
      - '**.yml'
      - '**.yaml'

jobs:
  build:
    name: Ansible Lint
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Ansible and ansible-lint
        run: |
          pip install ansible ansible-lint
          ansible-galaxy collection install -r requirements.yml --pre

      - name: Show all .yml files in repo (debug)
        run: |
          echo "Found YAML files:"
          find . -maxdepth 1 -type f \( -name "*.yml" -o -name "*.yaml" \)

      - name: Run ansible-lint on root YAML files only
        run: |
          find . -maxdepth 1 -type f \( -name "*.yml" -o -name "*.yaml" \) | xargs -r ansible-lint
