name: Ansible Playbook Linting

on:
  push:
    paths:
      - '**.yml'
      - '**.yaml'
  pull_request:
    paths:
      - '**.yml'
      - '**.yaml'

jobs:
  lint:
    name: Run ansible-lint
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Ansible and ansible-lint
        run: |
          pip install ansible ansible-lint
          if [ -f requirements.yml ]; then
            ansible-galaxy collection install -r requirements.yml --pre
          fi

      - name: Run ansible-lint recursively and capture output
        run: |
          mkdir -p artifacts
          echo "== ansible-lint run ==" > artifacts/ansible-lint.log
          find . -type f \( -name "*.yml" -o -name "*.yaml" \) \
            | tee -a artifacts/ansible-lint.log \
            | xargs -r ansible-lint >> artifacts/ansible-lint.log 2>&1 || true

      - name: Upload lint log as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ansible-lint-log
          path: artifacts/ansible-lint.log
