name: Ansible Playbook Linting

on:
  push:
    paths:
      - '**.yml'
      - '**.yaml'
  pull_request:
    paths:
      - '**.yml'
      - '**.yaml'

jobs:
  build:
    name: Ansible Lint
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Ansible and ansible-lint
        run: |
          pip install ansible ansible-lint
          ansible-galaxy collection install -r requirements.yml --pre

      - name: Create artifacts directory
        run: mkdir -p artifacts

      - name: Show all .yml files in repo (debug)
        run: |
          echo "Found YAML files:" > artifacts/ansible-lint.log
          find . -maxdepth 1 -type f \( -name "*.yml" -o -name "*.yaml" \) >> artifacts/ansible-lint.log

      - name: Run ansible-lint and capture output
        run: |
          find . -maxdepth 1 -type f \( -name "*.yml" -o -name "*.yaml" \) \
          | xargs -r ansible-lint >> artifacts/ansible-lint.log 2>&1 || true

      - name: Upload linting log as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ansible-lint-report
          path: artifacts/ansible-lint.log
