name: Run Ansible site.yml on EC2

on:
  workflow_dispatch:  # Manual trigger
  push:
    paths:
      - '**.yml'
      - '**.yaml'

jobs:
  run-ansible:
    name: Run Ansible site.yml with patching tag
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Ansible
        run: |
          pip install ansible

      - name: Configure SSH access to EC2
        run: |
          mkdir -p $HOME/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > $HOME/.ssh/id_rsa
          chmod 600 $HOME/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> $HOME/.ssh/known_hosts

      - name: Run Ansible playbook (site.yml)
        run: |
          ansible-playbook site.yml \
            -i "${{ secrets.EC2_HOST }}," \
            -u ${{ secrets.EC2_USER }} \
            --private-key $HOME/.ssh/id_rsa \
            --tags patching \
            --skip-tags repo_update
